version: "3.9"

services:
  nexus:
    build: .
    image: ireshmm/nexus:latest-casc
    volumes:
      - nexus-data:/nexus-data
    networks:
      - ci-network
    ports:
      - "8081:80"
    env_file:
      - .env-vars
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    secrets:
      - nexus-jenkins-user-id
      - nexus-jenkins-user-password
      - nexus-realease-reader-user-password

networks:
  ci-network:
    name: ci-network
volumes:
  nexus-data:

secrets:
  nexus-jenkins-user-id:
    file: ../secrets/nexus-jenkins-user-id
  nexus-jenkins-user-password:
    file: ../secrets/nexus-jenkins-user-password
  nexus-realease-reader-user-password:
    file: ../secrets/nexus-realease-reader-user-password
