version: "3"

services:
  httpd:
    build: httpd
    image: ireshmm/ci-reverse-proxy:0.0.1
    volumes:
      - certbot-certs:/usr/local/apache2/keys
    networks:
      - ci-network
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env-vars

  jenkins:
    build: jenkins
    image: ireshmm/jenkins:lts-jdk11-jsac
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock:rw
    networks:
      - ci-network
    ports:
      - "8080:8080"
    env_file:
      - .env-vars
    group_add:
      - '999'
    secrets:
      - github-app-id
      - github-app-privkey
      - nexus-jenkins-user-id
      - nexus-jenkins-user-password
      - generic-webhook-token
    environment:
      TZ: "Asia/Colombo"

  nexus:
    build: nexus
    image: ireshmm/nexus:latest-casc
    volumes:
      - nexus-data:/nexus-data
    networks:
      - ci-network
    ports:
      - "8081:80"
    env_file:
      - .env-vars
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    secrets:
      - nexus-jenkins-user-id
      - nexus-jenkins-user-password
      - nexus-realease-reader-user-password
    environment:
      TZ: "Asia/Colombo"
        
  sonarqube:
    image: ireshmm/sonarqube:latest
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - ci-network
    ports:
      - "8443:9000"
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - ci-network

networks:
  ci-network:
    name: ci-network
volumes:
  certbot-certs:
    external: true
    name: certbot-certs
  jenkins-data:
  nexus-data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data:
secrets:
  github-app-id:
    file: secrets/github-app-id
  github-app-privkey:
    file: secrets/github-app-privkey
  nexus-jenkins-user-id:
    file: secrets/nexus-jenkins-user-id
  nexus-jenkins-user-password:
    file: secrets/nexus-jenkins-user-password
  generic-webhook-token:
    file: secrets/generic-webhook-token
  nexus-realease-reader-user-password:
    file: secrets/nexus-realease-reader-user-password