version: "3.9"

services:
  jenkins:
    build: .
    image: ireshmm/jenkins:lts-jdk11-jsac
    volumes:
      - jenkins-data:/var/jenkins_home
    networks:
      - ci-network
    ports:
      - "8080:8080"
    environment:
      JENKINS_URL: "https://jenkins.nableintegration.ml/"
      GITHUB_ORG_NAME: "nable-integration-cicd-dev-mirror"
      GITHUB_APP_CRED_ID: "jenkins_github_app"
      JOB_CREATOR_DSL_REPO: "https://github.com/nable-integration-cicd-dev-mirror/JenkinsJobDSL.git"
      SHARED_LIB_REPO: "https://github.com/nable-integration-cicd-dev-mirror/JenkinsLibs.git"
      BUILD_SCRIPTS_REPO: "https://github.com/IreshMM/iresh-s-buildscripts.git"
      ACE_SHARED_LIB_INDEX_URL: "https://raw.githubusercontent.com/nable-integration-cicd-dev-mirror/ACESharedLibDirectory/master/libraries.csv"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
    group_add:
      - '999'
    secrets:
      - github-app-id
      - github-app-privkey
      - nexus-jenkins-user-id
      - nexus-jenkins-user-password
      - generic-webhook-token
      - jenkins-admin-password

networks:
  ci-network:
    name: ci-network
volumes:
  jenkins-data:
secrets:
  github-app-id:
    file: ../secrets/github-app-id
  github-app-privkey:
    file: ../secrets/github-app-privkey
  nexus-jenkins-user-id:
    file: ../secrets/nexus-jenkins-user-id
  nexus-jenkins-user-password:
    file: ../secrets/nexus-jenkins-user-password
  jenkins-admin-password:
    file: ../secrets/jenkins-admin-password
  generic-webhook-token:
    file: ../secrets/generic-webhook-token
