version: "3"

services:
  httpd:
    build: .
    image: ireshmm/ci-reverse-proxy:0.0.1
    volumes:
      - certbot-certs:/usr/local/apache2/keys
    networks:
      - ci-network
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAIN_DNS_NAME: nableintegration.ml
      SERVER_ADMIN_EMAIL: socialexpz1@gmail.com

volumes:
  certbot-certs:
    external: true
    name: certbot-certs
networks:
  ci-network:
    name: ci-network
