version: "3"

services:
  httpd:
    build: .
    image: ireshmm/ci-reverse-proxy:0.0.1
    volumes:
      - certbot-certs:/usr/local/apache2/keys
    networks:
      - ci-network
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env-vars

volumes:
  certbot-certs:
    external: true
    name: certbot-certs
networks:
  ci-network:
    name: ci-network
