version: "3"

services:
  httpd:
    image: ireshmm/ci-reverse-proxy:0.0.1
    volumes:
      - certbot-certs:/usr/local/apache2/keys
    ports:
      - "80:80"
      - "443:443"

volumes:
  certbot-certs:
    external: true
    name: certbot-certs
